dependencies:
- base >= 4.7 && < 5
- megaparsec
- prettyprinter
- prettyprinter-ansi-terminal
- haskeline
- mtl
- text
- transformers
- scientific
- parser-combinators
- containers
- bytestring
- zlib
- serialise 
- directory
- time
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hw3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3

tests:
  hw3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3
